/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'slot' : TimeSlot,
  'user' : Principal,
  'address' : string,
  'serviceId' : bigint,
  'petDetails' : PetDetails,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface PetDetails {
  'age' : bigint,
  'name' : string,
  'notes' : string,
  'breed' : string,
}
export interface Service {
  'duration' : bigint,
  'name' : string,
  'description' : string,
  'price' : bigint,
}
export interface TimeSlot { 'date' : string, 'time' : string }
export interface UserProfile { 'name' : string, 'address' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addService' : ActorMethod<[string, string, bigint, bigint], bigint>,
  'addTimeSlot' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBooking' : ActorMethod<[bigint], undefined>,
  'completeBooking' : ActorMethod<[bigint], undefined>,
  'confirmBooking' : ActorMethod<[bigint], undefined>,
  'createBooking' : ActorMethod<[bigint, TimeSlot, PetDetails, string], bigint>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAvailableTimeSlots' : ActorMethod<[string], Array<TimeSlot>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeTimeSlot' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];