/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TimeSlot = IDL.Record({ 'date' : IDL.Text, 'time' : IDL.Text });
export const PetDetails = IDL.Record({
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'breed' : IDL.Text,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'slot' : TimeSlot,
  'user' : IDL.Principal,
  'address' : IDL.Text,
  'serviceId' : IDL.Nat,
  'petDetails' : PetDetails,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Text,
});
export const Service = IDL.Record({
  'duration' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'addTimeSlot' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [], []),
  'completeBooking' : IDL.Func([IDL.Nat], [], []),
  'confirmBooking' : IDL.Func([IDL.Nat], [], []),
  'createBooking' : IDL.Func(
      [IDL.Nat, TimeSlot, PetDetails, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAvailableTimeSlots' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TimeSlot)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeTimeSlot' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TimeSlot = IDL.Record({ 'date' : IDL.Text, 'time' : IDL.Text });
  const PetDetails = IDL.Record({
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'breed' : IDL.Text,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'slot' : TimeSlot,
    'user' : IDL.Principal,
    'address' : IDL.Text,
    'serviceId' : IDL.Nat,
    'petDetails' : PetDetails,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'address' : IDL.Text });
  const Service = IDL.Record({
    'duration' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'addTimeSlot' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [], []),
    'completeBooking' : IDL.Func([IDL.Nat], [], []),
    'confirmBooking' : IDL.Func([IDL.Nat], [], []),
    'createBooking' : IDL.Func(
        [IDL.Nat, TimeSlot, PetDetails, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAvailableTimeSlots' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TimeSlot)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeTimeSlot' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };